name: voucho
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase & Backend
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  
  # State Management & Utils
  provider: ^6.1.5+1
  intl: any
  shared_preferences: ^2.5.4
  
  # Médias et Partage
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

# Configuration de l'icône
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0D1B1E"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# Configuration du Splash Screen (Écran de démarrage)
flutter_native_splash:
  color: "#0D1B1E"
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
    color: "#0D1B1E"

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_home.jpg
    - assets/images/ib.jpg
    - assets/images/im.webp
    - assets/images/app_icon.png