name: voucho_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # AJOUTE TES DÉPENDANCES ICI (Bien alignées sous 'flutter:')
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  provider: ^6.1.5+1
  intl: any
  firebase_analytics: ^12.1.0
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Pour tes polices et images plus tard :
  assets:
     - assets/images/bg_home.jpg
     - assets/images/ib.jpg
     - assets/images/im.webp